<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeter.proto

namespace GPBMetadata;

class Greeter
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abb010a0d677265657465722e70726f746f120767726565746572221c0a" .
            "0c48656c6c6f52657175657374120c0a046e616d65180120012809221d0a" .
            "0a48656c6c6f5265706c79120f0a076d6573736167651801200128093243" .
            "0a074772656574657212380a0853617948656c6c6f12152e677265657465" .
            "722e48656c6c6f526571756573741a132e677265657465722e48656c6c6f" .
            "5265706c79220042170a15636f6d2e7a73792e64656d6f2e677270632e6c" .
            "6962620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

